### ISSUE TITLE
사업자 마이페이지

### ISSUE THREAD

**Issue by kingseungil** [sparta-final/final-project#109]
![오류](https://user-images.githubusercontent.com/109774037/225316836-1b6a4072-de62-418c-a701-d09da76bdfef.gif)

사업자 마이페이지에서 사용자 누르면 데이터가 없다고 alert창 뜬 후 데이터 보임
+ 리뷰보기 글자 깨짐

**Comment by HxxJ-project** [comment]
alert창 뜨는건 수정해놨습니다.
