### ISSUE TITLE
멤버쉽 오류

### ISSUE THREAD

**Issue by kingseungil** [sparta-final/final-project#177]
![image](https://user-images.githubusercontent.com/109774037/226783804-fa13ce68-1207-4762-9a43-1a779c3a1e64.png)

내 멤버쉽들어가면 basic과 premium이 바껴있음
( DB에는 basic인데 프론트출력에는 premium으로)

**Comment by HxxJ-project** [comment]
해당이슈 디비 더미데이터 작업하면서 생긴 오류같습니다.
